### DISCUSSION TITLE
Issue with storage access folder

### DISCUSSION THREAD

**Discussion by Eri-tog** [jlesage/docker-freefilesync#14] [Q&A]
Hello! 
I have no problem deploying however it seems that I'm facing a permission issue in the GUI. When I try to access the folder "storage" I get the following error 'could not read the content of storage: permission denied'

Here is my compose, the user I'm running docker with is owner and creator of the folder media and its subfolders. He has read and write access on my server. would you know what I'm doing wrong?
```
version: '3'
services:
  freefilesync:
    container_name: freefilesync
    image: jlesage/freefilesync
    ports:
      - "5800:5800"
    environment:
      - PUID=1039 
      - PGID=65539 
      - TZ=America/Montreal 
    network_mode: synobridge
    volumes:
      - "/volume2/docker/freefilesync:/config:rw"
      - "/volume2/data/media:/storage:rw"
```

Thank you!
