### DISCUSSION TITLE
Can you give a complete case of Scheduled Batch Jobs?

### DISCUSSION THREAD

**Discussion by kokojacket** [jlesage/docker-freefilesync#7] [Q&A]
I don't know if I wrote it correctly，
      - FFS_SCHEDULED_BATCH_JOB_<ID>_NAME=test1
      - FFS_SCHEDULED_BATCH_JOB_<ID>_CRON=*/3 * * * *

**Comment by kokojacket** [comment]
I understand

**Comment by jlesage** [comment]
You are missing the ID.  So for example, if you chose ID `1`, you would set the environment variables like this:
```
- FFS_SCHEDULED_BATCH_JOB_1_NAME=test1
- FFS_SCHEDULED_BATCH_JOB_1_CRON=*/3 * * * *
```
And the batch job should be saved in the container at:
```
/config/test1.ffs_batch
```

**Reply by chop249** [reply]
@jlesage I'm trying to figure this out. I have the job I want saved in config as XXXX.ffs_batch but I'm lost as to where to put FF_SCHEDULED_BATCH_JOB_1_NAME=XXXX. I'm also lost as to how to configure the actual schedule. 😩😲

**Reply by kokojacket** [reply]
````
version: '3'

services:
  freefilesync:
    image: jlesage/freefilesync
    container_name: FreeFileSync
    restart: always
    ports:
      - "5800:5800"
    volumes:
      - "/mnt/130G/ddocker/FreeFileSync:/config:rw"
      - "/Synctest:/storage:rw"
      - "/Alist:/Alist:rw"
    environment:
      - VNC_PASSWORD=password

      - PUID=0    # 想切换为哪个用户来运行程序，该用户的uid
      - PGID=0    # 想切换为哪个用户来运行程序，该用户的gid
      - UMASK=000 # 掩码权限，默认000，可以考虑设置为022
      - ENABLE_CJK_FONT=1
      - FFS_SCHEDULED_BATCH_JOB_1_NAME=test1
      - FFS_SCHEDULED_BATCH_JOB_1_CRON=*/3 * * * *


````
