### ISSUE TITLE
[Bug] Unable to support Chinese fonts, please add Chinese font support, thank you! !

### ISSUE THREAD

**Issue by maosiyo** [jlesage/docker-freefilesync#12]
### Current Behavior

Unable to support Chinese fonts, please add Chinese font support, thank you! !
无法支持中文字体，请添加中文字体支持，谢谢！！

![image](https://github.com/jlesage/docker-freefilesync/assets/31647714/9d9e5d2a-fe9c-455b-a0e5-04d10213df8b)

![image](https://github.com/jlesage/docker-freefilesync/assets/31647714/a288c83a-2245-481b-8205-cac710bd3976)

### Expected Behavior

Normal display of Chinese font.

![image](https://github.com/jlesage/docker-freefilesync/assets/31647714/494ead01-1937-4210-b9d9-6cf061f28af2)

### Environment

- OS: Synology DSM 
- OS version: Synology DSM 7.2.1-69057 Update 1 
- CPU: INTEL Celeron J3455
- Docker version: 20.10.23 (API: 1.41)
- Device model: docker-compose
- Browser/OS: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

### Container creation

```yaml
version: "3"

services:
    free-file-sync:
        image: "jlesage/freefilesync:latest"
        container_name: free-file-sync
        restart: always
        networks:
            container-network: # port :5800
        volumes:
            - "/volume4/docker/mdc/free-file-sync/config:/config:rw"
            - "/volume4/data:/storage:rw"
        environment:
            - USER_ID=1026
            - GROUP_ID=100
            - SUP_GROUP_IDS=100,937
            - UMASK=0022
            # - LANG=zh_CN.UTF-8
            - TZ=Asia/Shanghai
            - VNC_PASSWORD=maosi@file-sync
        labels:
            - "traefik.enable=true"
            ## https 入口
            - "traefik.http.routers.free-file-sync.entrypoints=websecure"
            - "traefik.http.routers.free-file-sync.tls=true"
            - "traefik.http.routers.free-file-sync.rule=Host(`file-sync.maosiyo.com`)"
            - "traefik.http.routers.free-file-sync.service=free-file-sync"
            # https 端口
            - "traefik.http.services.free-file-sync.loadbalancer.server.port=5800"
            - "traefik.http.routers.free-file-sync.middlewares=gzip@docker"
            ## GZIP
            - "traefik.http.middlewares.gzip.compress=true"

networks:
    container-network:
        name: npm_hosts_bridge
        external: true
```

### Container log

```text
[cont-env    ] XDG_CONFIG_HOME: loading...
[cont-env    ] XDG_DATA_HOME: loading...
[cont-env    ] XDG_RUNTIME_DIR: loading...
[cont-env    ] XDG_STATE_HOME: loading...
[cont-env    ] container environment variables initialized.
[cont-secrets] loading container secrets...
[cont-secrets] container secrets loaded.
[cont-init   ] executing container initialization scripts...
[cont-init   ] 10-certs.sh: executing...
[cont-init   ] 10-certs.sh: terminated successfully.
[cont-init   ] 10-check-app-niceness.sh: executing...
[cont-init   ] 10-check-app-niceness.sh: terminated successfully.
[cont-init   ] 10-clean-logmonitor-states.sh: executing...
[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
[cont-init   ] 10-clean-tmp-dir.sh: executing...
[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
[cont-init   ] 10-fontconfig-cache-dir.sh: executing...
[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
[cont-init   ] 10-init-users.sh: executing...
[cont-init   ] 10-init-users.sh: terminated successfully.
[cont-init   ] 10-nginx.sh: executing...
[cont-init   ] 10-nginx.sh: terminated successfully.
[cont-init   ] 10-openbox.sh: executing...
[cont-init   ] 10-openbox.sh: terminated successfully.
[cont-init   ] 10-pkgs-mirror.sh: executing...
[cont-init   ] 10-pkgs-mirror.sh: terminated successfully.
[cont-init   ] 10-set-tmp-dir-perms.sh: executing...
[cont-init   ] 10-set-tmp-dir-perms.sh: terminated successfully.
[cont-init   ] 10-vnc-password.sh: executing...
[cont-init   ] 10-vnc-password.sh: creating VNC password file from environment variable...
[cont-init   ] 10-vnc-password.sh: terminated successfully.
[cont-init   ] 10-web-data.sh: executing...
[cont-init   ] 10-web-data.sh: terminated successfully.
[cont-init   ] 10-x11-unix.sh: executing...
[cont-init   ] 10-x11-unix.sh: terminated successfully.
[cont-init   ] 10-xdg-runtime-dir.sh: executing...
[cont-init   ] 10-xdg-runtime-dir.sh: terminated successfully.
[cont-init   ] 15-cjk-font.sh: executing...
[cont-init   ] 15-cjk-font.sh: terminated successfully.
[cont-init   ] 15-install-pkgs.sh: executing...
[cont-init   ] 15-install-pkgs.sh: terminated successfully.
[cont-init   ] 55-freefilesync.sh: executing...
[cont-init   ] 55-freefilesync.sh: terminated successfully.
[cont-init   ] 85-take-config-ownership.sh: executing...
[cont-init   ] 85-take-config-ownership.sh: terminated successfully.
[cont-init   ] 89-info.sh: executing...
    ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
    │                                                                      │
    │ Application:           FreeFileSync                                  │
    │ Application Version:   13.1                                          │
    │ Docker Image Version:  23.11.2                                       │
    │ Docker Image Platform: linux/amd64                                   │
    │                                                                      │
    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
[cont-init   ] 89-info.sh: terminated successfully.
[cont-init   ] all container initialization scripts executed.
[init        ] giving control to process supervisor.
[supervisor  ] loading services...
[supervisor  ] loading service 'default'...
[supervisor  ] loading service 'app'...
[supervisor  ] loading service 'gui'...
[supervisor  ] loading service 'certsmonitor'...
[supervisor  ] service 'certsmonitor' is disabled.
[supervisor  ] loading service 'nginx'...
[supervisor  ] loading service 'xvnc'...
[supervisor  ] loading service 'openbox'...
[supervisor  ] loading service 'logmonitor'...
[supervisor  ] service 'logmonitor' is disabled.
[supervisor  ] loading service 'logrotate'...
[supervisor  ] loading service 'crond'...
[supervisor  ] service 'crond' is disabled.
[supervisor  ] all services loaded.
[supervisor  ] starting services...
[supervisor  ] starting service 'xvnc'...
[xvnc        ] Xvnc TigerVNC 1.13.1 - built Nov 10 2023 13:43:39
[xvnc        ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
[xvnc        ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc        ] Underlying X server release 12014000
[xvnc        ] Sat Nov 18 16:23:43 2023
[xvnc        ]  vncext:      VNC extension running!
[xvnc        ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc        ]  vncext:      Listening for VNC connections on all interface(s), port 5900
[xvnc        ]  vncext:      created VNC server for screen 0
[supervisor  ] starting service 'nginx'...
[nginx       ] Listening for HTTP connections on port 5800.
[supervisor  ] starting service 'openbox'...
[supervisor  ] starting service 'app'...
[supervisor  ] all services started.
[app         ] (FreeFileSync:663): Gtk-CRITICAL **: 16:23:45.269: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed
[app         ] (FreeFileSync:663): Gtk-CRITICAL **: 16:23:45.271: gtk_widget_set_size_request: assertion 'width >= -1' failed
[app         ] (FreeFileSync:663): Gtk-CRITICAL **: 16:23:45.271: gtk_widget_set_size_request: assertion 'width >= -1' failed
[xvnc        ] Sat Nov 18 16:23:51 2023
[xvnc        ]  Connections: accepted: /tmp/vnc.sock
[xvnc        ]  SConnection: Client needs protocol version 3.8
[xvnc        ]  SConnection: Client requests security type VncAuth(2)
[xvnc        ] Sat Nov 18 16:23:58 2023
[xvnc        ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc        ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
```
